window.APP_DATA = {
  yanghua: {
    name: "Adult",
    label: "\u6210\u4eba",
    emoji: "\ud83d\udc69\u200d\ud83c\udf93",
    desc: "\u751f\u6d3b\u573a\u666f\u00b78\u4e2a\u8bed\u8a00\u5c9b\u00b7160\u53e5",
    color: "#EC4899",
    bg: "#FDF2F8",
    voice: { lang: "en-US", name: "Samantha", pitch: 1.0, rate: 0.9 },
    islands: [
      {
        name: "\u65e5\u5e38\u8d77\u5c45",
        nameEn: "Daily Routine",
        icon: "\u2601\ufe0f",
        sentences: [
          "I wake up at six o'clock every morning.",
          "I usually have coffee and toast for breakfast.",
          "I need to leave for work by seven thirty.",
          "What time do you usually go to bed?",
          "I'm going to take a shower now.",
          "Can you help me set the alarm for tomorrow?",
          "It takes me about twenty minutes to get ready.",
          "I like to read for a while before going to sleep.",
          "I overslept this morning.",
          "I need to do some laundry today.",
          "The weather is nice today, let's go for a walk.",
          "Can you turn off the lights, please?",
          "I usually check my phone first thing in the morning.",
          "Don't forget to take out the trash.",
          "I'm going to take a nap after lunch.",
          "What are your plans for this weekend?",
          "I always lock the door before I leave.",
          "The air conditioning is not working.",
          "I need to buy some cleaning supplies.",
          "It's already midnight, I should go to bed."
        ]
      },
      {
        name: "\u996e\u98df\u4e0e\u70f9\u996a",
        nameEn: "Food & Cooking",
        icon: "\ud83c\udf73",
        sentences: [
          "What would you like to eat for dinner?",
          "I'm going to cook some stir-fried vegetables tonight.",
          "Can you pass me the salt, please?",
          "This dish is delicious! What's in it?",
          "I prefer my coffee with a little sugar.",
          "Let's order some takeout, I don't feel like cooking.",
          "Do you have any dietary restrictions?",
          "The soup needs a bit more seasoning.",
          "I'll make some rice and steamed fish for lunch.",
          "Would you like another cup of tea?",
          "I'm trying to eat more vegetables these days.",
          "Can you help me chop these onions?",
          "Let's try that new restaurant down the street.",
          "I usually skip breakfast on busy mornings.",
          "The food here is really authentic.",
          "Do you know how to make hotpot at home?",
          "I bought some fresh fruits at the market.",
          "This tastes even better than last time.",
          "Let's save the leftovers for tomorrow.",
          "I'm in the mood for something spicy today."
        ]
      },
      {
        name: "\u793e\u4ea4\u4e0e\u95f2\u804a",
        nameEn: "Social & Chat",
        icon: "\ud83d\udc4b",
        sentences: [
          "Nice to meet you! Where are you from?",
          "What do you do for a living?",
          "How long have you been living in Haikou?",
          "The weather here is so nice all year round.",
          "Do you have any hobbies?",
          "I work at a maternal and child health center.",
          "Have you been to any interesting places lately?",
          "Let me introduce you to my colleague.",
          "That's a great idea! I totally agree with you.",
          "I'm originally from Hunan, but I moved here a few years ago.",
          "What do you usually do on weekends?",
          "Long time no see! How have you been?",
          "I really enjoy living in Hainan.",
          "Can I add you on WeChat?",
          "She is one of my closest friends.",
          "I heard there's a new coffee shop nearby.",
          "We should get together sometime soon.",
          "I'm not really into sports, but I like walking.",
          "That reminds me of a funny story.",
          "It was great talking to you. See you next time!"
        ]
      },
      {
        name: "\u8d2d\u7269\u4e0e\u6d88\u8d39",
        nameEn: "Shopping",
        icon: "\ud83d\uded2",
        sentences: [
          "How much is this?",
          "Do you accept mobile payment?",
          "Can I try this on?",
          "Is there any discount today?",
          "I'm just looking, thanks.",
          "Do you have this in a different color?",
          "I'd like to return this item, please.",
          "The quality is really good for the price.",
          "Can you give me a receipt?",
          "Is this on sale?",
          "I need to buy some groceries for the week.",
          "Where is the fitting room?",
          "Do you have anything cheaper?",
          "I'll take two of these, please.",
          "Can you wrap this as a gift?",
          "The supermarket is just around the corner.",
          "I prefer shopping online these days.",
          "This one doesn't fit me well.",
          "Do you deliver to this address?",
          "I spent too much money today."
        ]
      },
      {
        name: "\u4ea4\u901a\u51fa\u884c",
        nameEn: "Transport",
        icon: "\ud83d\ude97",
        sentences: [
          "How do I get to the train station from here?",
          "Is there a bus stop nearby?",
          "How long does it take by taxi?",
          "I missed the bus. When is the next one?",
          "Can you call a taxi for me, please?",
          "The traffic is really heavy right now.",
          "I usually ride my e-bike to work.",
          "Which platform does the train leave from?",
          "Is this seat taken?",
          "How much is the fare?",
          "I need to buy a round-trip ticket.",
          "The subway is much faster during rush hour.",
          "Can you drop me off at the corner?",
          "I'm running a bit late today.",
          "Where is the nearest parking lot?",
          "I prefer taking the high-speed train.",
          "Let me check the map for directions."
        ]
      },
      {
        name: "\u5065\u5eb7\u4e0e\u533b\u7597",
        nameEn: "Health & Medical",
        icon: "\ud83c\udfe5",
        sentences: [
          "I have a headache. Can you recommend some medicine?",
          "I need to make an appointment with the doctor.",
          "My throat has been sore for two days.",
          "Do I need to fast before the blood test?",
          "I'm allergic to penicillin.",
          "The doctor said I should get more rest.",
          "How many times a day should I take this medicine?",
          "I've been feeling very tired lately.",
          "Is there a pharmacy nearby?",
          "I need to get my annual checkup done.",
          "The fever has gone down, but I still have a cough.",
          "My blood pressure is a bit high.",
          "I twisted my ankle while walking.",
          "When should I come back for a follow-up?",
          "Make sure to drink plenty of water.",
          "I'd like to schedule a vaccination.",
          "The symptoms started about three days ago.",
          "Do you have a family history of diabetes?",
          "I've been exercising more to stay healthy.",
          "Remember to take your medicine after meals."
        ]
      },
      {
        name: "\u65c5\u884c\u4e0e\u4f4f\u5bbf",
        nameEn: "Travel & Hotel",
        icon: "\u2708\ufe0f",
        sentences: [
          "I'd like to book a room for two nights, please.",
          "Is breakfast included?",
          "What time is check-in?",
          "Can I have a late check-out?",
          "Is there WiFi in the room?",
          "Where is the nearest tourist attraction?",
          "I'd like to rent a car for the day.",
          "Can you recommend a good local restaurant?",
          "How do I get to the beach from here?",
          "The view from the room is amazing.",
          "I need to change my flight to a later date.",
          "Do you have any tours available?",
          "I'd like a room with a sea view, please.",
          "Is the swimming pool open all day?",
          "Can you call a taxi to the airport?",
          "What are the must-see places in this city?"
        ]
      },
      {
        name: "\u5174\u8da3\u4e0e\u81ea\u6211\u8868\u8fbe",
        nameEn: "Hobbies & Self-Expression",
        icon: "\ud83c\udfa8",
        sentences: [
          "In my free time, I enjoy reading and cooking.",
          "I've been learning English for a few months now.",
          "Music helps me relax after a long day at work.",
          "I'd like to travel more in the future.",
          "I think learning new things keeps you young.",
          "I'm interested in traditional Chinese medicine.",
          "Reading is my favorite way to unwind.",
          "I want to improve my English so I can travel abroad.",
          "I believe health is the most important thing in life.",
          "I enjoy watching documentaries about nature.",
          "I've been trying to learn more about nutrition.",
          "Sometimes I write in a journal before bed.",
          "I find gardening very therapeutic.",
          "My dream is to visit Europe someday.",
          "I think it's never too late to learn something new.",
          "I like to practice English by talking to myself.",
          "Cooking for my family makes me happy.",
          "I want to set a good example for my child.",
          "I feel grateful for everything in my life.",
          "I'm working on becoming a better version of myself."
        ]
      }
    ]
  },
  mumu: {
    name: "Child",
    label: "\u513f\u7ae5",
    emoji: "\ud83d\udc66",
    desc: "\u5b66\u6821+\u5174\u8da3+\u5bb6\u5ead\u00b78\u4e2a\u8bed\u8a00\u5c9b\u00b7148\u53e5",
    color: "#F59E0B",
    bg: "#FFFBEB",
    voice: { lang: "en-US", name: "Junior", pitch: 1.0, rate: 0.85 },
    islands: [
      {
        name: "\u5b66\u6821\u65e5\u5e38",
        nameEn: "School Daily",
        icon: "\ud83c\udfeb",
        sentences: [
          "Good morning, teacher.",
          "May I come in?",
          "May I go to the bathroom?",
          "I don't understand. Can you explain again?",
          "Can I borrow a pencil?",
          "I forgot my homework at home.",
          "When is the next class?",
          "It's time for lunch.",
          "Let's go play on the playground.",
          "School is over. Let's go home.",
          "I need to go to the library.",
          "The bell is ringing. Let's line up.",
          "I like art class the most.",
          "Can you help me with this problem?",
          "I finished my homework.",
          "Today's lunch is delicious.",
          "I got an A on my test!",
          "We have PE class this afternoon.",
          "I need to buy a new notebook.",
          "Let's review for the exam together."
        ]
      },
      {
        name: "\u8bfe\u5802\u56de\u7b54\u4e0e\u63d0\u95ee",
        nameEn: "Classroom Q&A",
        icon: "\ud83d\udcdd",
        sentences: [
          "I know the answer! It's...",
          "Can I ask a question?",
          "I think the answer is twelve.",
          "I'm not sure about this one.",
          "May I speak, please?",
          "What page are we on?",
          "I don't know how to spell this word.",
          "Can you repeat that, please?",
          "I agree with what he said.",
          "I have a different idea.",
          "Could you speak a little slower, please?",
          "What does this word mean?",
          "I need more time to think.",
          "The answer is wrong. Let me try again.",
          "I understand now. Thank you!",
          "Can I share my answer with the class?",
          "I think I made a mistake here.",
          "That's a very good question!"
        ]
      },
      {
        name: "\u540c\u5b66\u793e\u4ea4",
        nameEn: "Friends",
        icon: "\ud83e\udd1d",
        sentences: [
          "Do you want to play together?",
          "Let's be friends!",
          "Can I sit next to you?",
          "What's your favorite game?",
          "That was really fun!",
          "I'm sorry. I didn't mean to.",
          "Let's play hide and seek.",
          "You're really good at this!",
          "Want to trade snacks?",
          "I'll save you a seat.",
          "See you tomorrow!",
          "Good luck on the test!",
          "That's so funny!",
          "Can I join your team?",
          "Let me help you with that.",
          "You're my best friend.",
          "Do you want to come to my house?",
          "I was thinking about you.",
          "Let's play after school.",
          "Don't tell anyone, okay?"
        ]
      },
      {
        name: "\u5bb6\u5ead\u65e5\u5e38",
        nameEn: "Family Daily",
        icon: "\ud83c\udfe0",
        sentences: [
          "Mom, I'm home!",
          "What's for dinner tonight?",
          "Can I watch TV for a little while?",
          "I need help with my homework.",
          "Can I have some water, please?",
          "I finished all my homework.",
          "It's time to take a bath.",
          "Good night, Mom. Good night, Dad.",
          "Can I invite my friend over?",
          "I'm hungry. Is there anything to eat?",
          "I can't find my school bag.",
          "Mom, can you buy me a new toy?",
          "Let me help you set the table.",
          "I cleaned my room today.",
          "Can we go to the park this weekend?",
          "I got a star from my teacher today!",
          "Dad, look what I made!",
          "Can I play on the tablet for ten minutes?",
          "I love our family.",
          "What day is it today?"
        ]
      },
      {
        name: "\u5bb6\u5ead\u60c5\u611f\u8868\u8fbe",
        nameEn: "Family Feelings",
        icon: "\u2764\ufe0f",
        sentences: [
          "I love you, Mom.",
          "Thank you for helping me.",
          "I'm sorry I was naughty today.",
          "I'm so happy today!",
          "I miss Grandpa and Grandma.",
          "Mom, you're the best!",
          "I feel sad because my friend is sick.",
          "I'm proud of myself!",
          "Can I give you a hug?",
          "You look pretty today, Mom.",
          "I was scared of the dark last night.",
          "I'm excited about the weekend!",
          "Dad, can we play together?",
          "I feel much better now.",
          "Thank you for the delicious food.",
          "I want to make you proud.",
          "I feel nervous about the test tomorrow.",
          "I had a really good day at school."
        ]
      },
      {
        name: "\u640f\u51fb\u8bfe",
        nameEn: "Martial Arts",
        icon: "\ud83e\udd4a",
        sentences: [
          "Coach, I'm ready!",
          "Let me try that move again.",
          "I need to practice my left hook.",
          "That was a great kick!",
          "Keep your hands up!",
          "My legs are sore from yesterday's training.",
          "I want to learn that combo.",
          "Can we do some sparring today?",
          "I need to improve my footwork.",
          "Coach, did I do that right?",
          "Let's warm up first.",
          "I'm getting better at blocking!",
          "That punch was really fast!",
          "I feel stronger than last week.",
          "Can you show me that technique one more time?",
          "Good job! Keep it up!",
          "Time to cool down and stretch."
        ]
      },
      {
        name: "\u8fd0\u52a8\u4e0e\u6e38\u620f",
        nameEn: "Sports & Games",
        icon: "\u26bd",
        sentences: [
          "Let's play soccer!",
          "Pass the ball to me!",
          "That was a great goal!",
          "I want to be on that team.",
          "Let's play basketball after school.",
          "I love swimming in the summer.",
          "Can we ride our bikes to the park?",
          "I ran really fast today!",
          "Let's play tag. You're it!",
          "I want to learn to ride a skateboard.",
          "Which sport is your favorite?",
          "I scored three points today!",
          "The water is too cold for swimming.",
          "Let's have a race!",
          "I need to stretch before I run.",
          "We won the game! Hooray!",
          "I like playing video games too.",
          "Shall we play chess?",
          "I caught the ball!"
        ]
      },
      {
        name: "\u52a8\u7269\u4e0e\u81ea\u7136",
        nameEn: "Animals & Nature",
        icon: "\ud83e\udd8c",
        sentences: [
          "I love cats. They're so cute!",
          "Look at that butterfly!",
          "The dog is wagging its tail.",
          "I want to see the dolphins at the aquarium.",
          "What's your favorite animal?",
          "The sunset is so beautiful today.",
          "I can hear the birds singing.",
          "It's raining outside. Let's stay in.",
          "Look at the stars tonight!",
          "The flowers in the garden are blooming.",
          "I saw a squirrel in the park.",
          "The ocean is so blue and clear.",
          "I want to plant a tree.",
          "The caterpillar turned into a butterfly!",
          "Let's go catch some fish.",
          "I love watching the clouds change shapes."
        ]
      }
    ]
  }
};
