window.APP_DATA = {
  yanghua: {
    name: "Adult",
    label: "\u6210\u4eba",
    emoji: "\ud83d\udc69\u200d\ud83c\udf93",
    desc: "\u751f\u6d3b\u573a\u666f\u00b78\u4e2a\u8bed\u8a00\u5c9b\u00b7160\u53e5",
    color: "#EC4899",
    bg: "#FDF2F8",
    voice: { lang: "en-US", name: "Samantha", pitch: 1.0, rate: 0.9 },
    islands: [
      {
        name: "\u65e5\u5e38\u8d77\u5c45",
        nameEn: "Daily Routine",
        icon: "\u2601\ufe0f",
        sentences: [{en:"I wake up at six o'clock every morning.",zh:"我每天早上六点起床。"},
{en:"I usually have coffee and toast for breakfast.",zh:"我早餐通常喝咖啡吃吐司。"},
{en:"I need to leave for work by seven thirty.",zh:"我七点半前得出门上班。"},
{en:"What time do you usually go to bed?",zh:"你通常几点睡觉？"},
{en:"I'm going to take a shower now.",zh:"我现在去洗个澡。"},
{en:"Can you help me set the alarm for tomorrow?",zh:"你能帮我设一下明天的闹钟吗？"},
{en:"It takes me about twenty minutes to get ready.",zh:"我大概需要二十分钟准备出门。"},
{en:"I like to read for a while before going to sleep.",zh:"我喜欢睡前看一会儿书。"},
{en:"I overslept this morning.",zh:"今早我睡过头了。"},
{en:"I need to do some laundry today.",zh:"我今天得洗些衣服。"},
{en:"The weather is nice today, let's go for a walk.",zh:"今天天气不错，我们出去走走吧。"},
{en:"Can you turn off the lights, please?",zh:"请把灯关一下好吗？"},
{en:"I usually check my phone first thing in the morning.",zh:"我早上第一件事就是看手机。"},
{en:"Don't forget to take out the trash.",zh:"别忘了把垃圾丢出去。"},
{en:"I'm going to take a nap after lunch.",zh:"午饭后我要小睡一会儿。"},
{en:"What are your plans for this weekend?",zh:"你周末有什么计划？"},
{en:"I always lock the door before I leave.",zh:"我出门前都会锁门。"},
{en:"The air conditioning is not working.",zh:"空调坏了。"},
{en:"I need to buy some cleaning supplies.",zh:"我需要买些清洁用品。"},
{en:"It's already midnight, I should go to bed.",zh:"已经午夜了，我该睡觉了。"}]
      },
      {
        name: "\u996e\u98df\u4e0e\u70f9\u996a",
        nameEn: "Food & Cooking",
        icon: "\ud83c\udf73",
        sentences: [{en:"What would you like to eat for dinner?",zh:"晚饭你想吃什么？"},
{en:"I'm going to cook some stir-fried vegetables tonight.",zh:"今晚我打算炒些蔬菜。"},
{en:"Can you pass me the salt, please?",zh:"请把盐递给我好吗？"},
{en:"This dish is delicious! What's in it?",zh:"这道菜太好吃了！里面放了什么？"},
{en:"I prefer my coffee with a little sugar.",zh:"我喝咖啡喜欢加一点糖。"},
{en:"Let's order some takeout, I don't feel like cooking.",zh:"我们点外卖吧，我不想做饭了。"},
{en:"Do you have any dietary restrictions?",zh:"你有什么饮食禁忌吗？"},
{en:"The soup needs a bit more seasoning.",zh:"这汤还需要再多加点调料。"},
{en:"I'll make some rice and steamed fish for lunch.",zh:"午饭我做米饭和清蒸鱼。"},
{en:"Would you like another cup of tea?",zh:"再喝一杯茶吗？"},
{en:"I'm trying to eat more vegetables these days.",zh:"这些天我在尽量多吃蔬菜。"},
{en:"Can you help me chop these onions?",zh:"你能帮我切一下洋葱吗？"},
{en:"Let's try that new restaurant down the street.",zh:"我们去试试街角那家新开的餐厅吧。"},
{en:"I usually skip breakfast on busy mornings.",zh:"忙的时候我经常不吃早餐。"},
{en:"The food here is really authentic.",zh:"这里的菜真的很地道。"},
{en:"Do you know how to make hotpot at home?",zh:"你会在家做火锅吗？"},
{en:"I bought some fresh fruits at the market.",zh:"我在市场买了一些新鲜水果。"},
{en:"This tastes even better than last time.",zh:"这比上次做的还好吃。"},
{en:"Let's save the leftovers for tomorrow.",zh:"我们把剩菜留着明天吃吧。"},
{en:"I'm in the mood for something spicy today.",zh:"今天我想吃点辣的。"}]
      },
      {
        name: "\u793e\u4ea4\u4e0e\u95f2\u804a",
        nameEn: "Social & Chat",
        icon: "\ud83d\udc4b",
        sentences: [{en:"Nice to meet you! Where are you from?",zh:"很高兴认识你！你是哪里人？"},
{en:"What do you do for a living?",zh:"你是做什么工作的？"},
{en:"How long have you been living in Haikou?",zh:"你在海口住了多久了？"},
{en:"The weather here is so nice all year round.",zh:"这里一年四季天气都很好。"},
{en:"Do you have any hobbies?",zh:"你有什么爱好吗？"},
{en:"I work at a maternal and child health center.",zh:"我在妇幼保健所工作。"},
{en:"Have you been to any interesting places lately?",zh:"最近有没有去什么有趣的地方？"},
{en:"Let me introduce you to my colleague.",zh:"我给你介绍一下我的同事。"},
{en:"That's a great idea! I totally agree with you.",zh:"好主意！我完全同意你的看法。"},
{en:"I'm originally from Hunan, but I moved here a few years ago.",zh:"我老家是湖南的，几年前搬到这儿来了。"},
{en:"What do you usually do on weekends?",zh:"你周末通常做什么？"},
{en:"Long time no see! How have you been?",zh:"好久不见！你最近怎么样？"},
{en:"I really enjoy living in Hainan.",zh:"我很喜欢住在海南。"},
{en:"Can I add you on WeChat?",zh:"我能加你微信吗？"},
{en:"She is one of my closest friends.",zh:"她是我最要好的朋友之一。"},
{en:"I heard there's a new coffee shop nearby.",zh:"听说附近开了一家新咖啡店。"},
{en:"We should get together sometime soon.",zh:"我们最近应该聚一聚。"},
{en:"I'm not really into sports, but I like walking.",zh:"我不太爱运动，但喜欢散步。"},
{en:"That reminds me of a funny story.",zh:"这让我想起一件有趣的事。"},
{en:"It was great talking to you. See you next time!",zh:"和你聊天很愉快，下次见！"}]
      },
      {
        name: "\u8d2d\u7269\u4e0e\u6d88\u8d39",
        nameEn: "Shopping",
        icon: "\ud83d\uded2",
        sentences: [{en:"How much is this?",zh:"这个多少钱？"},
{en:"Do you accept mobile payment?",zh:"可以用手机支付吗？"},
{en:"Can I try this on?",zh:"我可以试穿一下吗？"},
{en:"Is there any discount today?",zh:"今天有折扣吗？"},
{en:"I'm just looking, thanks.",zh:"我只是看看，谢谢。"},
{en:"Do you have this in a different color?",zh:"这个有其他颜色吗？"},
{en:"I'd like to return this item, please.",zh:"我想退掉这件商品。"},
{en:"The quality is really good for the price.",zh:"这个价格来说质量真的很好。"},
{en:"Can you give me a receipt?",zh:"请给我一张收据。"},
{en:"Is this on sale?",zh:"这个在打折吗？"},
{en:"I need to buy some groceries for the week.",zh:"我需要买些一周的菜。"},
{en:"Where is the fitting room?",zh:"试衣间在哪里？"},
{en:"Do you have anything cheaper?",zh:"有便宜一点的吗？"},
{en:"I'll take two of these, please.",zh:"我要两个这个。"},
{en:"Can you wrap this as a gift?",zh:"能把这个包装成礼品吗？"},
{en:"The supermarket is just around the corner.",zh:"超市就在拐角处。"},
{en:"I prefer shopping online these days.",zh:"我最近更喜欢网购。"},
{en:"This one doesn't fit me well.",zh:"这个不太合身。"},
{en:"Do you deliver to this address?",zh:"你们送到这个地址吗？"},
{en:"I spent too much money today.",zh:"今天花太多钱了。"}]
      },
      {
        name: "\u4ea4\u901a\u51fa\u884c",
        nameEn: "Transport",
        icon: "\ud83d\ude97",
        sentences: [{en:"How do I get to the train station from here?",zh:"从这儿去火车站怎么走？"},
{en:"Is there a bus stop nearby?",zh:"附近有公交站吗？"},
{en:"How long does it take by taxi?",zh:"打车需要多长时间？"},
{en:"I missed the bus. When is the next one?",zh:"我没赶上公交，下一班什么时候？"},
{en:"Can you call a taxi for me, please?",zh:"你能帮我叫一辆出租车吗？"},
{en:"The traffic is really heavy right now.",zh:"现在路况真的很堵。"},
{en:"I usually ride my e-bike to work.",zh:"我通常骑电动车上班。"},
{en:"Which platform does the train leave from?",zh:"火车从哪个站台出发？"},
{en:"Is this seat taken?",zh:"这个座位有人吗？"},
{en:"How much is the fare?",zh:"车费多少钱？"},
{en:"I need to buy a round-trip ticket.",zh:"我需要买一张往返票。"},
{en:"The subway is much faster during rush hour.",zh:"高峰时段地铁快多了。"},
{en:"Can you drop me off at the corner?",zh:"能在拐角让我下车吗？"},
{en:"I'm running a bit late today.",zh:"我今天有点晚了。"},
{en:"Where is the nearest parking lot?",zh:"最近的停车场在哪里？"},
{en:"I prefer taking the high-speed train.",zh:"我更愿意坐高铁。"},
{en:"Let me check the map for directions.",zh:"我看看地图导航。"}]
      },
      {
        name: "\u5065\u5eb7\u4e0e\u533b\u7597",
        nameEn: "Health & Medical",
        icon: "\ud83c\udfe5",
        sentences: [{en:"I have a headache. Can you recommend some medicine?",zh:"我头疼，能推荐些药吗？"},
{en:"I need to make an appointment with the doctor.",zh:"我需要预约看医生。"},
{en:"My throat has been sore for two days.",zh:"我嗓子疼了两天了。"},
{en:"Do I need to fast before the blood test?",zh:"抽血前需要空腹吗？"},
{en:"I'm allergic to penicillin.",zh:"我对青霉素过敏。"},
{en:"The doctor said I should get more rest.",zh:"医生说我应该多休息。"},
{en:"How many times a day should I take this medicine?",zh:"这个药一天吃几次？"},
{en:"I've been feeling very tired lately.",zh:"我最近一直觉得很累。"},
{en:"Is there a pharmacy nearby?",zh:"附近有药店吗？"},
{en:"I need to get my annual checkup done.",zh:"我需要做年度体检。"},
{en:"The fever has gone down, but I still have a cough.",zh:"烧退了，但还在咳嗽。"},
{en:"My blood pressure is a bit high.",zh:"我的血压有点高。"},
{en:"I twisted my ankle while walking.",zh:"走路时扭了脚。"},
{en:"When should I come back for a follow-up?",zh:"什么时候来复查？"},
{en:"Make sure to drink plenty of water.",zh:"一定要多喝水。"},
{en:"I'd like to schedule a vaccination.",zh:"我想预约接种疫苗。"},
{en:"The symptoms started about three days ago.",zh:"症状大约三天前开始的。"},
{en:"Do you have a family history of diabetes?",zh:"有糖尿病家族史吗？"},
{en:"I've been exercising more to stay healthy.",zh:"我最近多运动来保持健康。"},
{en:"Remember to take your medicine after meals.",zh:"记得饭后吃药。"}]
      },
      {
        name: "\u65c5\u884c\u4e0e\u4f4f\u5bbf",
        nameEn: "Travel & Hotel",
        icon: "\u2708\ufe0f",
        sentences: [{en:"I'd like to book a room for two nights, please.",zh:"我想订两晚的房间。"},
{en:"Is breakfast included?",zh:"含早餐吗？"},
{en:"What time is check-in?",zh:"几点可以入住？"},
{en:"Can I have a late check-out?",zh:"可以延迟退房吗？"},
{en:"Is there WiFi in the room?",zh:"房间有WiFi吗？"},
{en:"Where is the nearest tourist attraction?",zh:"最近的景点在哪里？"},
{en:"I'd like to rent a car for the day.",zh:"我想租一天车。"},
{en:"Can you recommend a good local restaurant?",zh:"能推荐一家当地的好餐厅吗？"},
{en:"How do I get to the beach from here?",zh:"从这儿去海滩怎么走？"},
{en:"The view from the room is amazing.",zh:"房间的风景很棒。"},
{en:"I need to change my flight to a later date.",zh:"我需要把航班改到更晚的日期。"},
{en:"Do you have any tours available?",zh:"你们有旅游团可以参加吗？"},
{en:"I'd like a room with a sea view, please.",zh:"请给我一间海景房。"},
{en:"Is the swimming pool open all day?",zh:"泳池全天开放吗？"},
{en:"Can you call a taxi to the airport?",zh:"能叫一辆去机场的出租车吗？"},
{en:"What are the must-see places in this city?",zh:"这座城市有哪些必去的地方？"}]
      },
      {
        name: "\u5174\u8da3\u4e0e\u81ea\u6211\u8868\u8fbe",
        nameEn: "Hobbies & Self-Expression",
        icon: "\ud83c\udfa8",
        sentences: [{en:"In my free time, I enjoy reading and cooking.",zh:"空闲时我喜欢阅读和做饭。"},
{en:"I've been learning English for a few months now.",zh:"我学英语已经几个月了。"},
{en:"Music helps me relax after a long day at work.",zh:"音乐让我在忙碌一天后放松下来。"},
{en:"I'd like to travel more in the future.",zh:"将来我想多旅行。"},
{en:"I think learning new things keeps you young.",zh:"我觉得学习新东西能让人保持年轻。"},
{en:"I'm interested in traditional Chinese medicine.",zh:"我对中医很感兴趣。"},
{en:"Reading is my favorite way to unwind.",zh:"阅读是我最喜欢的放松方式。"},
{en:"I want to improve my English so I can travel abroad.",zh:"我想提高英语水平，将来能出国旅行。"},
{en:"I believe health is the most important thing in life.",zh:"我认为健康是人生中最重要的。"},
{en:"I enjoy watching documentaries about nature.",zh:"我喜欢看自然纪录片。"},
{en:"I've been trying to learn more about nutrition.",zh:"我最近在多了解营养学知识。"},
{en:"Sometimes I write in a journal before bed.",zh:"有时候我睡前会写日记。"},
{en:"I find gardening very therapeutic.",zh:"我觉得园艺很有疗愈效果。"},
{en:"My dream is to visit Europe someday.",zh:"我的梦想是有一天去欧洲。"},
{en:"I think it's never too late to learn something new.",zh:"我觉得学什么都不会太晚。"},
{en:"I like to practice English by talking to myself.",zh:"我喜欢自言自语来练习英语。"},
{en:"Cooking for my family makes me happy.",zh:"为家人做饭让我感到幸福。"},
{en:"I want to set a good example for my child.",zh:"我想给孩子做个好榜样。"},
{en:"I feel grateful for everything in my life.",zh:"我感恩生活中的一切。"},
{en:"I'm working on becoming a better version of myself.",zh:"我正在努力成为更好的自己。"}]
      }
    ]
  },
  mumu: {
    name: "Child",
    label: "\u513f\u7ae5",
    emoji: "\ud83d\udc66",
    desc: "\u5b66\u6821+\u5174\u8da3+\u5bb6\u5ead\u00b78\u4e2a\u8bed\u8a00\u5c9b\u00b7148\u53e5",
    color: "#F59E0B",
    bg: "#FFFBEB",
    voice: { lang: "en-US", name: "Junior", pitch: 1.0, rate: 0.85 },
    islands: [
      {
        name: "\u5b66\u6821\u65e5\u5e38",
        nameEn: "School Daily",
        icon: "\ud83c\udfeb",
        sentences: [{en:"Good morning, teacher.",zh:"老师早上好。"},
{en:"May I come in?",zh:"我可以进来吗？"},
{en:"May I go to the bathroom?",zh:"我可以去洗手间吗？"},
{en:"I don't understand. Can you explain again?",zh:"我不明白，能再讲一遍吗？"},
{en:"Can I borrow a pencil?",zh:"能借我一支铅笔吗？"},
{en:"I forgot my homework at home.",zh:"我把作业忘在家了。"},
{en:"When is the next class?",zh:"下一节课是什么时候？"},
{en:"It's time for lunch.",zh:"该吃午饭了。"},
{en:"Let's go play on the playground.",zh:"我们去操场玩吧！"},
{en:"School is over. Let's go home.",zh:"放学了，我们回家吧。"},
{en:"I need to go to the library.",zh:"我需要去图书馆。"},
{en:"The bell is ringing. Let's line up.",zh:"打铃了，我们排队吧。"},
{en:"I like art class the most.",zh:"我最喜欢上美术课。"},
{en:"Can you help me with this problem?",zh:"你能帮我看看这道题吗？"},
{en:"I finished my homework.",zh:"我做完作业了。"},
{en:"Today's lunch is delicious.",zh:"今天的午饭很好吃。"},
{en:"I got an A on my test!",zh:"我考试得了A！"},
{en:"We have PE class this afternoon.",zh:"今天下午有体育课。"},
{en:"I need to buy a new notebook.",zh:"我需要买一个新笔记本。"},
{en:"Let's review for the exam together.",zh:"我们一起复习考试吧。"}]
      },
      {
        name: "\u8bfe\u5802\u56de\u7b54\u4e0e\u63d0\u95ee",
        nameEn: "Classroom Q&A",
        icon: "\ud83d\udcdd",
        sentences: [{en:"I know the answer! It's...",zh:"我知道答案！是……"},
{en:"Can I ask a question?",zh:"我能问个问题吗？"},
{en:"I think the answer is twelve.",zh:"我觉得答案是十二。"},
{en:"I'm not sure about this one.",zh:"这道我不太确定。"},
{en:"May I speak, please?",zh:"我能发言吗？"},
{en:"What page are we on?",zh:"我们翻到哪一页了？"},
{en:"I don't know how to spell this word.",zh:"我不知道这个词怎么拼。"},
{en:"Can you repeat that, please?",zh:"能再说一遍吗？"},
{en:"I agree with what he said.",zh:"我同意他说的。"},
{en:"I have a different idea.",zh:"我有一个不同的想法。"},
{en:"Could you speak a little slower, please?",zh:"能说慢一点吗？"},
{en:"What does this word mean?",zh:"这个词是什么意思？"},
{en:"I need more time to think.",zh:"我需要多想一会儿。"},
{en:"The answer is wrong. Let me try again.",zh:"答案错了，让我再试一次。"},
{en:"I understand now. Thank you!",zh:"我现在明白了，谢谢！"},
{en:"Can I share my answer with the class?",zh:"我可以和全班分享我的答案吗？"},
{en:"I think I made a mistake here.",zh:"我觉得这里我弄错了。"},
{en:"That's a very good question!",zh:"这是一个很好的问题！"}]
      },
      {
        name: "\u540c\u5b66\u793e\u4ea4",
        nameEn: "Friends",
        icon: "\ud83e\udd1d",
        sentences: [{en:"Do you want to play together?",zh:"你想一起玩吗？"},
{en:"Let's be friends!",zh:"我们做朋友吧！"},
{en:"Can I sit next to you?",zh:"我能坐在你旁边吗？"},
{en:"What's your favorite game?",zh:"你最喜欢的游戏是什么？"},
{en:"That was really fun!",zh:"刚才真的好好玩！"},
{en:"I'm sorry. I didn't mean to.",zh:"对不起，我不是故意的。"},
{en:"Let's play hide and seek.",zh:"我们玩捉迷藏吧。"},
{en:"You're really good at this!",zh:"你真的很厉害！"},
{en:"Want to trade snacks?",zh:"要交换零食吗？"},
{en:"I'll save you a seat.",zh:"我帮你占座。"},
{en:"See you tomorrow!",zh:"明天见！"},
{en:"Good luck on the test!",zh:"考试加油！"},
{en:"That's so funny!",zh:"太好笑了！"},
{en:"Can I join your team?",zh:"我能加入你的队伍吗？"},
{en:"Let me help you with that.",zh:"让我帮你吧。"},
{en:"You're my best friend.",zh:"你是我最好的朋友。"},
{en:"Do you want to come to my house?",zh:"想来我家玩吗？"},
{en:"I was thinking about you.",zh:"我想你了。"},
{en:"Let's play after school.",zh:"放学后一起玩吧。"},
{en:"Don't tell anyone, okay?",zh:"别告诉别人，好吗？"}]
      },
      {
        name: "\u5bb6\u5ead\u65e5\u5e38",
        nameEn: "Family Daily",
        icon: "\ud83c\udfe0",
        sentences: [{en:"Mom, I'm home!",zh:"妈妈，我回来了！"},
{en:"What's for dinner tonight?",zh:"今晚吃什么？"},
{en:"Can I watch TV for a little while?",zh:"我能看一会儿电视吗？"},
{en:"I need help with my homework.",zh:"我需要你帮我辅导作业。"},
{en:"Can I have some water, please?",zh:"能给我倒点水吗？"},
{en:"I finished all my homework.",zh:"我作业全做完了。"},
{en:"It's time to take a bath.",zh:"该洗澡了。"},
{en:"Good night, Mom. Good night, Dad.",zh:"晚安，妈妈。晚安，爸爸。"},
{en:"Can I invite my friend over?",zh:"我能邀请朋友来家里吗？"},
{en:"I'm hungry. Is there anything to eat?",zh:"我饿了，有什么吃的吗？"},
{en:"I can't find my school bag.",zh:"我找不到书包了。"},
{en:"Mom, can you buy me a new toy?",zh:"妈妈，能给我买个新玩具吗？"},
{en:"Let me help you set the table.",zh:"让我帮你摆碗筷吧。"},
{en:"I cleaned my room today.",zh:"我今天打扫了房间。"},
{en:"Can we go to the park this weekend?",zh:"这周末能去公园吗？"},
{en:"I got a star from my teacher today!",zh:"今天老师奖了我一颗星！"},
{en:"Dad, look what I made!",zh:"爸爸，看我做的东西！"},
{en:"Can I play on the tablet for ten minutes?",zh:"我能玩十分钟平板吗？"},
{en:"I love our family.",zh:"我爱我们家。"},
{en:"What day is it today?",zh:"今天星期几？"}]
      },
      {
        name: "\u5bb6\u5ead\u60c5\u611f\u8868\u8fbe",
        nameEn: "Family Feelings",
        icon: "\u2764\ufe0f",
        sentences: [{en:"I love you, Mom.",zh:"妈妈我爱你。"},
{en:"Thank you for helping me.",zh:"谢谢你帮我。"},
{en:"I'm sorry I was naughty today.",zh:"对不起，今天我调皮了。"},
{en:"I'm so happy today!",zh:"今天我好开心！"},
{en:"I miss Grandpa and Grandma.",zh:"我想爷爷奶奶了。"},
{en:"Mom, you're the best!",zh:"妈妈，你是最好的！"},
{en:"I feel sad because my friend is sick.",zh:"我朋友生病了，我很难过。"},
{en:"I'm proud of myself!",zh:"我为自己感到骄傲！"},
{en:"Can I give you a hug?",zh:"我能抱你一下吗？"},
{en:"You look pretty today, Mom.",zh:"妈妈，你今天好漂亮。"},
{en:"I was scared of the dark last night.",zh:"昨晚我怕黑了。"},
{en:"I'm excited about the weekend!",zh:"我对周末很期待！"},
{en:"Dad, can we play together?",zh:"爸爸，我们一起玩好吗？"},
{en:"I feel much better now.",zh:"我现在感觉好多了。"},
{en:"Thank you for the delicious food.",zh:"谢谢您做了这么好吃的饭菜。"},
{en:"I want to make you proud.",zh:"我想让你们为我骄傲。"},
{en:"I feel nervous about the test tomorrow.",zh:"我有点紧张，明天要考试。"},
{en:"I had a really good day at school.",zh:"今天在学校度过了很棒的一天。"}]
      },
      {
        name: "\u640f\u51fb\u8bfe",
        nameEn: "Martial Arts",
        icon: "\ud83e\udd4a",
        sentences: [{en:"Coach, I'm ready!",zh:"教练，我准备好了！"},
{en:"Let me try that move again.",zh:"让我再试一次那个动作。"},
{en:"I need to practice my left hook.",zh:"我需要多练左钩拳。"},
{en:"That was a great kick!",zh:"那一踢太漂亮了！"},
{en:"Keep your hands up!",zh:"双手举起来！"},
{en:"My legs are sore from yesterday's training.",zh:"昨天训练完我腿很酸痛。"},
{en:"I want to learn that combo.",zh:"我想学那套组合拳。"},
{en:"Can we do some sparring today?",zh:"今天能对练吗？"},
{en:"I need to improve my footwork.",zh:"我需要改善步法。"},
{en:"Coach, did I do that right?",zh:"教练，我做得对吗？"},
{en:"Let's warm up first.",zh:"我们先热身。"},
{en:"I'm getting better at blocking!",zh:"我的防守越来越好了！"},
{en:"That punch was really fast!",zh:"那一拳好快！"},
{en:"I feel stronger than last week.",zh:"我比上周感觉更强壮了。"},
{en:"Can you show me that technique one more time?",zh:"能再示范一次那个动作吗？"},
{en:"Good job! Keep it up!",zh:"做得好！继续保持！"},
{en:"Time to cool down and stretch.",zh:"该放松拉伸了。"}]
      },
      {
        name: "\u8fd0\u52a8\u4e0e\u6e38\u620f",
        nameEn: "Sports & Games",
        icon: "\u26bd",
        sentences: [{en:"Let's play soccer!",zh:"踢足球吧！"},
{en:"Pass the ball to me!",zh:"传给我！"},
{en:"That was a great goal!",zh:"那个球进得太漂亮了！"},
{en:"I want to be on that team.",zh:"我想进那个队。"},
{en:"Let's play basketball after school.",zh:"放学后打篮球吧。"},
{en:"I love swimming in the summer.",zh:"夏天我最爱游泳。"},
{en:"Can we ride our bikes to the park?",zh:"能骑车去公园吗？"},
{en:"I ran really fast today!",zh:"今天我跑得真快！"},
{en:"Let's play tag. You're it!",zh:"玩抓人游戏吧，轮到你抓了！"},
{en:"I want to learn to ride a skateboard.",zh:"我想学滑板。"},
{en:"Which sport is your favorite?",zh:"你最喜欢什么运动？"},
{en:"I scored three points today!",zh:"今天我得了三分！"},
{en:"The water is too cold for swimming.",zh:"水太冷了不能游泳。"},
{en:"Let's have a race!",zh:"我们赛跑吧！"},
{en:"I need to stretch before I run.",zh:"跑步前我需要拉伸。"},
{en:"We won the game! Hooray!",zh:"我们赢了！耶！"},
{en:"I like playing video games too.",zh:"我也喜欢玩电子游戏。"},
{en:"Shall we play chess?",zh:"我们下棋吧？"},
{en:"I caught the ball!",zh:"我接到球了！"}]
      },
      {
        name: "\u52a8\u7269\u4e0e\u81ea\u7136",
        nameEn: "Animals & Nature",
        icon: "\ud83e\udd8c",
        sentences: [{en:"I love cats. They're so cute!",zh:"我喜欢猫咪，太可爱了！"},
{en:"Look at that butterfly!",zh:"看那只蝴蝶！"},
{en:"The dog is wagging its tail.",zh:"狗狗在摇尾巴。"},
{en:"I want to see the dolphins at the aquarium.",zh:"我想去水族馆看海豚。"},
{en:"What's your favorite animal?",zh:"你最喜欢的动物是什么？"},
{en:"The sunset is so beautiful today.",zh:"今天的日落好美。"},
{en:"I can hear the birds singing.",zh:"我能听到鸟儿在唱歌。"},
{en:"It's raining outside. Let's stay in.",zh:"外面下雨了，我们待在屋里吧。"},
{en:"Look at the stars tonight!",zh:"看今晚的星星！"},
{en:"The flowers in the garden are blooming.",zh:"花园里的花都开了。"},
{en:"I saw a squirrel in the park.",zh:"我在公园看到了一只松鼠。"},
{en:"The ocean is so blue and clear.",zh:"大海好蓝好清澈。"},
{en:"I want to plant a tree.",zh:"我想种一棵树。"},
{en:"The caterpillar turned into a butterfly!",zh:"毛毛虫变成蝴蝶了！"},
{en:"Let's go catch some fish.",zh:"我们去抓鱼吧。"},
{en:"I love watching the clouds change shapes.",zh:"我喜欢看云朵变换形状。"}]
      }
    ]
  }
};
